### ISSUE TITLE
pen_down artifact disappears

### ISSUE THREAD

**Issue by lmeeden1** [ArtificialIntelligenceToolkit/aitk.robots#10]
The trace left behind by doing a pen_down should be permanent, at least until it is requested to be erased.

**Comment by dsblank** [comment]
Can you explain more? When does it go away?

**Comment by lmeeden1** [comment]
See the new notebook ExplorePen.  I can't seem to get the color to change nor the radius to change.  How do the trace and the pen_down interact?  Does one need to turn off the trace to see the pen artifact?

**Comment by dsblank** [comment]
See new ExplorePen.ipynb
