### ISSUE TITLE
problem with watching and saving a recorder

### ISSUE THREAD

**Issue by lmeeden1** [ArtificialIntelligenceToolkit/aitk.robots#4]
The following code generates the error message below.  The save_as method also has the same issue.

```
recorder = world.record()
world.seconds(120,[wander_ir, wander_laser, search_light],real_time=False)
recorder.watch()
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/opt/miniconda3/envs/py38/lib/python3.8/site-packages/aitk/robots/watchers.py in <lambda>(widget)
    540             layout=Layout(width="100%"),
    541         )
--> 542         controls.on_displayed(lambda widget: self.initialize())
    543         return controls
    544 

~/opt/miniconda3/envs/py38/lib/python3.8/site-packages/aitk/robots/watchers.py in initialize(self)
    547         Setup the displayer ids to map results to the areas.
    548         """
--> 549         results = self.function(self.control_slider.value)
    550         if not isinstance(results, (list, tuple)):
    551             results = [results]

~/opt/miniconda3/envs/py38/lib/python3.8/site-packages/aitk/robots/watchers.py in goto(self, time)
    378         if self.world.time == 0:
    379             # In case it changed:
--> 380             self.world.reset_ground_image()
    381         self.world.update()
    382         picture = self.world.display(format="image")

AttributeError: 'World' object has no attribute 'reset_ground_image'

**Comment by dsblank** [comment]
Good catch! Fixed in version 0.8.5
