### ISSUE TITLE
watching a recorder generates a new error

### ISSUE THREAD

**Issue by lmeeden1** [ArtificialIntelligenceToolkit/aitk.robots#5]
`recorder.watch()`

generates an error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/miniconda3/envs/py38/lib/python3.8/site-packages/aitk/robots/watchers.py in <lambda>(widget)
    540             layout=Layout(width="100%"),
    541         )
--> 542         controls.on_displayed(lambda widget: self.initialize())
    543         return controls
    544 

~/opt/miniconda3/envs/py38/lib/python3.8/site-packages/aitk/robots/watchers.py in initialize(self)
    547         Setup the displayer ids to map results to the areas.
    548         """
--> 549         results = self.function(self.control_slider.value)
    550         if not isinstance(results, (list, tuple)):
    551             results = [results]

~/opt/miniconda3/envs/py38/lib/python3.8/site-packages/aitk/robots/watchers.py in goto(self, time)
    380             self.world._reset_ground_image()
    381         self.world.update()
--> 382         picture = self.world.display(format="image")
    383         return picture
    384 

TypeError: display() got an unexpected keyword argument 'format'
​

**Comment by dsblank** [comment]
Thanks! Have a proper test for that now too: aa0f3cdb152a6ed8e5ada859c31167f95dedfbc9 Released as version 0.8.6
