### ISSUE TITLE
robot.info should include robot's color and perhaps it's pose as well

### ISSUE THREAD

**Issue by lmeeden1** [ArtificialIntelligenceToolkit/aitk.robots#6]
Knowing the color and location of a particular robot would help distinguish it in a world with multiple robots.

**Comment by dsblank** [comment]
True, but the color is not guaranteed to be something nice like "yellow"... it could be #2367FF88 which doesn't help. Pose would probably help.

You can also:

```python
robot.get_image()
```
which shows something like:

![Screenshot from 2021-03-17 10-47-58](https://user-images.githubusercontent.com/168568/111513649-43b29100-870e-11eb-8d3a-19724aadd502.png)

**Comment by dsblank** [comment]
Added pose to robot representation:

```python
In [1]: from aitk.robots import World, Vehicle

In [2]: w = World()
Random seed set to: 5062279

In [3]: w.add_robot(Vehicle())

In [4]: w.robots
Out[4]: [<Robot(name='Vickie', x=225, y=109, a=162.04)>]

In [5]: w.robots[0].info()
  This robot has no devices.

In [6]: w.robots[0]
Out[6]: <Robot(name='Vickie', x=225, y=109, a=162.04)>

In [7]: w.info()
Size: 500 x 250
Robots:
-------------------------
  .robots[0 or 'Vickie']: <Robot(name='Vickie', x=225, y=109, a=162.04)>
  This robot has no devices.
```
